bazelrc: Remove hash_tracer from `query` sub-command
`cquery` seems to inherit `build`, so we don't need to add it to the
`query` sub-command.

This fixes:
```
ERROR: --aspects :: Unrecognized option: --aspects
```

BUG=b:302001628
TEST=BOARD=amd64-generic bazel query @portage//internal/sdk/stage2

Change-Id: Ie6ab7bb5a96bac6d32fa6605fccef1e31ecc401a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/bazel/+/4898181
Commit-Queue: Tim Bain <tbain@google.com>
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Tim Bain <tbain@google.com>
Tested-by: Raul Rangel <rrangel@chromium.org>