mountsdk: Check password-less sudo before running actual commands
When a build step fails because password-less sudo is not permitted,
the error is a bit hard to read:

sudo: a terminal is required to read the password; either use the -S
option to read from standard input or configure an askpass helper
sudo: a password is required
sudo: a terminal is required to read the password; either use the -S
option to read from standard input or configure an askpass helper
sudo: a password is required
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
ExitStatus(unix_wait_status(256)): sudo rm -rf /tmp/.tmpJgfSSb',
bazel/ebuild/private/common/mountsdk/src/mountsdk.rs:189:69

This patch makes the error more debuggable by checking sudo in advance
and printing a friendly error message.

BUG=None
TEST=BOARD=amd64-generic bazel build //:chromiumos_minimal_image

Change-Id: Ide1be806dd2520571a65111edbf1528f22f98dd1
Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/cros-bazel/+/1781168
Reviewed-by: Tomasz Tylenda <ttylenda@google.com>