alchemist: Print out nice error message if board doesn't exist
Example:
```
ERROR: no such package '@_main~portage~portage_digest//': Error running command [/home/rrangel/.cache/bazel/_bazel_rrangel/e517ea39ecb43168812d1d21bda62f96/external/_main~portage~alchemist/alchemist, "--board", "eve", "--source-dir", /mnt/host/source, "digest-repo"]:
ERROR:
*****
		You are running inside the CrOS SDK and `/build/eve` doesn't exist.

		Please run the following command to create the board's sysroot and try again:
		$ setup_board --board eve --profile base --skip-chroot-upgrade --skip-toolchain-update

*****

Stack backtrace:
```

BUG=b:303439620
TEST=cargo test
TEST=BOARD=amd64-generic bazel build @portage//sys-kernel/linux-headers
TEST=(cr) BOARD=amd64-generic bazel build @portage//sys-kernel/linux-headers

Change-Id: I7a42c6de7fd8c2e6b236ff8bed253f599e5fa786
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/bazel/+/4912022
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>