alchemist: Require host board to be present inside the chroot
Right now we get a very confusing error message when trying to build if
the `host` sysroot hasn't been setup when building inside the cros_sdk.

Since `stage2` has officially landed it's time to make the host board
required. This change will print out a nice error message if the host
board hasn't been setup when running in the SDK. It also won't silently
fail if the host board fails to load when running outside of the SDK.

This prints out the following error inside the chroot:
```
ERROR: no such package '@_main~portage~portage_digest//': Error running command [/home/rrangel/.cache/bazel/_bazel_rrangel/e517ea39ecb43168812d1d21bda62f96/external/_main~portage~alchemist/alchemist, "--board", "amd64-generic", "--source-dir", /mnt/host/source, "digest-repo"]:
ERROR:
*****
		You are running inside the CrOS SDK and `/build/amd64-host` doesn't exist.

		Please run the following command to create the host sysroot and try again:
		$ ~/chromiumos/src/scripts/create_sdk_board_root --board amd64-host --profile sdk/bootstrap

*****

Stack backtrace:
   0: alchemist::alchemist::alchemist_main
   1: alchemist::main
```

I added the extra spacing to make it easier to notice the error and
action item.

BUG=b:303439620
TEST=cargo test
TEST=BOARD=amd64-generic bazel build @portage//sys-kernel/linux-headers
TEST=(cr) BOARD=amd64-generic bazel build @portage//sys-kernel/linux-headers

Change-Id: Id8c0c2b4d3ce101ed27e2de8adc4cf61c5be3650
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/bazel/+/4912021
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>