build_sdk: Fix missing transition
```
ERROR: /home/rrangel/chromiumos/src/bazel/portage/build_defs/build_sdk.bzl:70:17: Use of Starlark transition without allowlist attribute '_allowlist_function_transition'. See Starlark transitions documentation for details and usage: //bazel/portage/build_defs:build_sdk.bzl NORMAL
```
BUG=none
TEST=BOARD=arm64-generic bazel run -k  @portage//internal/packages/stage2/target/board/chromiumos/dev-libs/nss:3.68.2-r3_debug

Fixes: 1effe86d ("Ensure specific targets always use primordial toolchain.")
Change-Id: I43f67ed1957cae2e414571c15873864622dc4375
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/bazel/+/4670706
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>